### PR TITLE
Add support for transportable packages

### LINKED ISSUE #5: Clone and pull repos into transportable packages
Currently we clone and pull only in local $ packages. We should add a option to clone into transportable packages and then check the transport request. It should contain all deserialized objects. Maybe also releasing the transport and purge with a new one.

### PR DESCRIPTION
**Pull request by flaiker**
Fixes #5 

Draft pull request for now.

If enabled in the selection screen the repos will also get installed into a Z-package. A transport request is created for pull and a different one for delete. Both get checked for their contents after release -> whether or not all repo objects are contained in the transport.

CTS seems to do stuff asynchronously in some cases so I added COMMIT WORK and SLEEP at some points to prevent race conditions.

TODOS:
- [x] Use transport layer from selection screen
- [x] Add documentation somewhere on how to setup CTS on AS ABAP dev edition
- [x] Figure out how DEVC should be handled
  - abapGit does not add the top level DEVC object to the deletion request, right?
  - Do the lower level packages get deleted?
  - ~~Currently abapGit CI seems to create the Z___ packages without adding them to a transport, even though the layer enforces recording (?!)~~ -> Had it locked in a different transport
- [x] Add a pre-check to see if there are still open transports from the previous CI-run with repo objects before pull (?) -> cleanup utility can mass release transports
- [x] Update documentation in readme
- [x] Add additional columns in the output table for the transport checks
- [x] Re-enable all other repos, remove breakpoints

### CODE REVIEW

**Comment by flaiker** [comment]
I added a small cleanup report `ZABAPGIT_CI_CLEANUP` to mass uninstall repos by package name and to mass release transport requests/tasks.

I also caught the RFC error message in 78542172bfc8e811882ebe4af0bb5b02f37b69dc for #35 (not really related to this PR).

**Comment by flaiker** [comment]
Regarding packages:
I don't think you can delete a package in the same transport as its containing object as the catalog entries still exist with delflag set. To check package deletion (and creation in the next run) one would have to generate another transport (3 instead of 2). For now I therefore ignored the DEVC objects in check_leftovers and check_transport_requests.

**Comment by flaiker** [comment]
Hmm weird. Looks like the checks weren't executed at all as if the parameter was set to false. Even though the screenshot shows it as checked. Did any transport requests get generated? Can you open the variant in the job step in SM37 to double check if `REPOT` is `X`?

I must admit I haven't had a background finish as I did not bother adding additional batch processes yet.

**Comment by christianguenter2** [comment]
That's the variant.
image

There were lot's of transports created, but I didn't yet configure my transport landscape right. Just was curious to run it without. I'll try more stuff tomorrow.

**Comment by christianguenter2** [comment]
OK, seems was due to missing transport landscape configuration. Now they show up.
image

A few transports were unreleased.
image

And one repo remains in the system, but had a dump for that in ST22.
image

image

**Comment by christianguenter2** [comment]
Seems that this feature reveals lot of problems. I think we should decide later whether these are real problems and if not exclude the somehow from CI.

**Comment by flaiker** [comment]
> Seems that this feature reveals lot of problems. I think we should decide later whether these are real abapGit problems and if not exclude the somehow from CI.

Can you upload the results of the run somewhere? We should refactor the ignore-thing so you can control in one place whether to ignore a test-repo only in transportable packages, only in local packages or both.

**Comment by christianguenter2** [comment]
@flaiker 
latest results are available ci.abapgit.org

**Pull request merged**
