### PR TITLE
Fix syntax errors

### PR DESCRIPTION
**Pull request by flaiker**
I had a quick go at actually using the new interfaces but lots of used methods are not part of these so it would be a larger refactoring.

### CODE REVIEW

**Comment by mbtools** [comment]
This CI process is THE use case of what the new interface should include meaning the full life-cycle of a repo (@sbcgua).

Thanks for taking the first go at it. We will need to add to the interface and keep adjusting this CI repo...

**Comment by larshp** [comment]
@mbtools so, can we merge this change?

**Comment by sbcgua** [comment]
Just a note: I included just most typical methods in the interface so far. Longterm-wise, I think that most of current zcl_repo methods should **NOT** be a part of the interface. But it is not visible at the moment. So we have 2 approaches:

1) copy all methods into the interface now (and then, remove one-by-one, when the time comes)
2) or use `lo_repo ?= ii_repo` workaround, keeping the interface clean.

I personally would choose the 2st. Though obviously it is less convenient. And the repo refactoring plans have no deadlines ... so ... I don't know. Just a comment.

**Comment by sbcgua** [comment]
BTW, looking through the code: `uninstall_repos` does it need the full repo instance ? get_package and get_name should be in the interface ...

**Comment by mbtools** [comment]
I agree that only a subset of the methods need to be in the interface. Here are the methods used by this CI repo and missing in the interface:

- `delete_checks`
- `deserialize_checks`
- `deserialize`
- `get_dot_abapgit`
- `status`

My suggestion was to add those as a next step.

This PR is good to merge. We can switch more to the interface when the remaining methods are available.

**Comment by larshp** [comment]
cool, merging

things will change, we need it to change, hopefully the cross check will help discovering bugs earlier 😄

**Comment by sbcgua** [comment]
> I agree that only a subset of the methods need to be in the interface. Here are the methods used by this CI repo and missing in the interface:
> 
> * `delete_checks`
> * `deserialize_checks`
> * `deserialize`
> * `get_dot_abapgit`
> * `status`
> 
> My suggestion was to add those as a next step.
> 
> This PR is good to merge. We can switch more to the interface when the remaining methods are available.

- 1-4 agree. by the way, am I the only one to find `_checks` suffix unclear ? Maybe it should be some kind of `dryrun` flag of the no-check method? Would make it semantically clearer. Just an idea.
- `status` - this could be arguable :P I'd actually remove it at all and extract the status calculation to a separate class. So it should be other class' operation **over** a repo. It would decrease load on repo class. And would make it easier to get local/remote files in parallel. Also just idea to mention.

**Comment by larshp** [comment]
should be reported with next abaplint release, https://github.com/abaplint/abaplint/pull/2417

**Pull request merged**
